Bugfix: Subdomain Detection for local embeds
epiphyt/embed-privacy pull request #52
Opened 2021-03-24 10:54 UTC by xwolfde

WP can run  on a subdomain itself (e.g. blog.abc.de). If we want to check for subdomains with a local embed provider (e.g. myembed.abc.de), we have to look for subdomains  of our main domain (abc.de), not for subdomains of the WP domain  (e.g. something.blog.abc.de).

2021-03-24 12:15 UTC, MatzeKitt commented
Thank you for pull request!

Please apply code styling:
- [ ] Always use `’` instead of `"` where possible.
- [ ] Braces are always followed by an empty space.
- [ ] `else if` should start on a new line.

2021-03-24 12:18 UTC, MatzeKitt requested changes
Thank you for pull request!

Please apply code styling:
- [ ] Always use `’` instead of `"` where possible.
- [ ] Braces are always followed by an empty space.
- [ ] `else if` should start on a new line.

2021-03-24 12:18 UTC, MatzeKitt commented on inc/class-embed-privacy.php
> +		$domain = $host = $parsed_url['host'];
Why do you define two variables with identical value here?

2021-03-24 12:18 UTC, MatzeKitt commented on inc/class-embed-privacy.php
> +		    $count = count($domain_array);
Please add a newline after this.

2021-03-24 12:18 UTC, MatzeKitt commented on inc/class-embed-privacy.php
> +		if ((!filter_var($host,FILTER_VALIDATE_IP)) && ($host !== 'localhost')) {
There is a wide variety of hosts that don’t need to be processed here. We should not add specific non-configurable hosts here.

2021-03-24 12:18 UTC, MatzeKitt commented on inc/class-embed-privacy.php
> +
Please remove these lines.

2021-03-24 12:18 UTC, MatzeKitt commented on inc/class-embed-privacy.php
> +
Please remove empty lines above.

2021-04-08 21:09 UTC, xwolfde commented
ich ziehe den Pull request zurück

2021-04-08 21:09 UTC, closed without merging