Add wrapper class to p element containing the checkbox to always load embed provider
epiphyt/embed-privacy pull request #54
Opened 2021-03-24 14:35 UTC by florianbrinkmann

It is not a big deal to select the `p` via `p:last-child` but maybe a class would make it a little easier :)

2021-03-29 09:48 UTC, MatzeKitt requested changes
I would love to see also the `p:last-child` replaced by your added class within the SCSS.

2021-03-29 11:08 UTC, florianbrinkmann commented
Done @MatzeKitt!

2021-04-10 17:57 UTC, MatzeKitt approved these changes

2021-04-10 17:58 UTC, MatzeKitt commented
Thank you! I will merge it as soon as development for v1.4.0 starts.

2021-12-16 18:05 UTC, merged